/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'jeff' at '8/11/16 9:28 AM' with Gradle 2.14.1
 *
 * @author jeff, @date 8/11/16 9:28 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
